# Generated by Django 5.2 on 2025-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_nota_nota_atividade_alter_nota_nota_prova_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=200)),
                ('livro', models.CharField(max_length=200)),
                ('nome_autor', models.CharField(max_length=200)),
                ('nome_genero', models.CharField(max_length=200)),
                ('nome_editora', models.CharField(max_length=200)),
                ('num_paginas', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
