# Generated by Django 5.2 on 2025-07-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_livro_delete_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='nome_aluno',
            new_name='nome_usuario',
        ),
        migrations.AlterField(
            model_name='livro',
            name='num_paginas',
            field=models.IntegerField(max_length=5),
        ),
    ]
